import Head from "next/head";

export default function Profile() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="flex h-screen w-full flex-col border-x md:max-w-4xl">
          <div className="flex flex-row items-center justify-center gap-4 border-b p-4">
            <p className="text-5xl font-bold">Profile Page</p>
          </div>
        </div>
      </main>
    </>
  );
}
